apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:5NBhTA29xl/X5lZR6rZOwUeg3ZHWYAhH8dm7JWRgH4Jm92fl1kAeV6TkhKHsUrZoYb3XDlA=,iv:KUSAeJdJnM6m7B3Ywzcn5ZNi140aNPGjur/ocnH45b0=,tag:3xomuMVmz2HS9h9UV5CsZQ==,type:str]
sops:
    age:
        - recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZ3JTRnVWYm1WNDhCWE56
            RHVrK0JhblNWYWxiUHFlMTU0Ky9GaVQ0WmtBCko0MXBmWU03dWNFa1JHZ2diekV5
            NjUvTy9aallONG1JSkFCdFVvb2R0Y00KLS0tIGVsem51amdnQ3VFOHp0Z0xYUnBS
            RkRaMEVYQjM2Q0tKK29kM29YRkJ2RkUKqLR2tfOobKRSoKvpHZjBDpCjAdLWpfJz
            U1RqzZ3k7QQ97wjXAfNWmXCvv0FDoBs5Ujlp6sBvV3tY/BF8QLrRnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T23:42:01Z"
    mac: ENC[AES256_GCM,data:cUgr7Xk5JWV0HAQG+MLNoH+uIFf7TDARpsLpKwNP+elmC5s4w9erU9El0BTSdwwFlh6+US6sPf6rMnCD/jdm7IucZcvyNJCX2gLdUceFtVFICtVOHIb6XYJ+U7n4gAuXcez20BJ7x65ya5UW/7S6E3WqLSIZ14zA87wRuupk0Vo=,iv:qfqwWIlm955M6ZGsDBdar4kaYCTs5dXfsre2OyDTe6o=,tag:U37gQbo3kNBLqPmMJwPEAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
