apiVersion: batch/v1
kind: CronJob
metadata:
  name: universe-update-orders
  labels:
    app: mrakaki-universe-update-orders
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mrakaki-universe-update-orders
        spec:
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: universe-update-orders
              image: mrakaki/dev-containers:mrakaki-eve-universe.0.0.5
              imagePullPolicy: IfNotPresent
              command: ["updateOrders"]
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: production
                - name: SPRING_CONFIG_IMPORT
                  value: "configserver:http://configuration:8888"
              resources:
                requests:
                  cpu: 100m
                  memory: 384Mi
                limits:
                  memory: 768Mi
