apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-attachment.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - storageclass-lh-rwx.yaml
  - storageclass-lh-block.yaml
  - storageclass-lh-slow-rwx.yaml
  - storageclass-lh-slow-block.yaml
