apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared
resources:
  - ../../../../apps/immich
  - pvc-upload-data.yaml
  - pvc-model-cache.yaml
  - secret.yaml
patches:
  - path: service-dualstack-server-patch.yaml
  - path: service-dualstack-ml-patch.yaml
  - path: deployment-server-node-selector-patch.yaml
  - target:
      version: v1
      kind: Deployment
      name: immich-server
    path: deployment-upload-data-pvc-json-patch.yaml
  - target:
      version: v1
      kind: Deployment
      name: immich-machine-learning
    path: deployment-ml-model-cache-pvc-json-patch.yaml
images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v3.1.0 # {"$imagepolicy":"flux-system:immich-server:tag"}
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v3.1.0 # {"$imagepolicy":"flux-system:immich-machine-learning:tag"}
