apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lh-fast-block
  resources:
    requests:
      storage: 750Gi
