apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lh-fast-block
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload-data-alex
  namespace: shared
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: lh-slow-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload-data-ana
  namespace: shared
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: lh-slow-block
