apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-uploads
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 30Gi
