apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
type: Opaque
stringData:
    DB_HOSTNAME: ENC[AES256_GCM,data:IMEf/arkZ6pBUCPMs9cTZmjPJAaepDKV9pvbed8270sTl8M=,iv:B2GS3mUORjqtIc8OErL9+wpAEjptuDzlIIGutJPturU=,tag:/k8yeFYcpCeDL3X6Asd3FA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:Jo9o+g==,iv:x+VYZv+YXqqX9KTs2JKlWhjMeUK7SpaDg6/nxHhHc8M=,tag:odV7nDML+cxCztZTz/SVIw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:fUiX32Jnt49q6+p+Eg==,iv:4AdL/VzXNqCL6UONh5qKMhbYX2nMtL8SE+u3BXF+2i8=,tag:cvj0AbnQg73mNtZEnpxzHQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ZgjVGTDqhmDbLC0c3+o0VcifGty5K2Co6nk=,iv:KHw/y99KYYvnkCNJCACQ15CkvdSigfbcq4i0iWUnFkk=,tag:3QlyRsb7/w0B/2uRCn26Ug==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:WATSlYjZC//XO57k0Q==,iv:mzESZujGK5L4Ow14AyT3801HtEz8rGPhBWwrQ8ZsuRU=,tag:4gpIVvZkjqeT6loVbJvbHg==,type:str]
    REDIS_HOSTNAME: ENC[AES256_GCM,data:u3DetFI86lrqkl2TU59LGRX97DGPFqLmTKoykD/4KNoU2oF8GCqvxK8x,iv:DKBQ+iw4hH8mE0q96iz6EvDKgfzez7mZhVJ79TmSUfU=,tag:hSA8MpU4eIXxc/UhckwTVg==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:LH43Qw==,iv:74VnWy4p5Yg2azd4l+pG67WH8Rf1mLx03wRzlvLLVCg=,tag:UdBabJ//IxqIBMbxxrtF2Q==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:0QvU7RhWf38NSoe+J8Ss+AEXufP6UGwUHkmnlTiLjH0=,iv:13No+UoQ3Tv3X33Rw7ochPfCnW1K0hCaDZGxArUNKR4=,tag:Xs21VRPI5ED29k0eJG3oZg==,type:str]
    REDIS_DBINDEX: ENC[AES256_GCM,data:jA==,iv:NaJM3zlGXLUBq8EM2VA1oR/sUG+PMXUARwF9djRsoXw=,tag:r/hvJPsCQAMnCOqr/lCSpw==,type:str]
sops:
    age:
        - recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YnpxZ1JLWStNTWIrUmp0
            OGFrMktyUFdnN2U5TFczY1pwN0twUjZHN2lzCkJlMlNrV1Q4UjN1ay9Mclo2U2RL
            RHQ4TFpiUk9scURhVGtVTlEzdGl1UGsKLS0tIDAzOUhvT2FnczRvVFU1ZjRpTHJl
            NWN4dGcrd1FndHBSaXlPUWlCNFMvb2cK4xw9rE/8ezJiuEXScL+9yjwBBj6M4eBl
            eLCv1nPI6M7NFtE0pIULgp34ZCU0oW+ii9YcPjlvrEAm2ScrK3kgSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T02:47:17Z"
    mac: ENC[AES256_GCM,data:knKyDqNXk0TAOrZDBZzS27twtu958sasCf0L2FCeIv+jFKEineKB8pCzEThrPkB6fqY2FmbLLgfuZ6A06CDYN7ZIwMS2T+OCHtUXy3jFqi4EbNkQTtpUQ5395HilXPg/9WLeteSWDJaa83pSHNY9zGC6hafj/VhCrZooOxfjVcs=,iv:6QaezZYWE5jcGqKOL2z9ZTeSTeTpe0cYeQLETTJjPmg=,tag:usEEURRBxX2dBRSjRJ4vUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
