apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
spec:
  ports:
    - port: 3003
      targetPort: 2283
      protocol: TCP
      name: http
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack
