apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
type: Opaque
stringData:
    #ENC[AES256_GCM,data:9nILkGfLLv+jx/xGFhxlX+Vnjrk7mKWV9Py3lc22VE+4i8ICL6GOnk9n,iv:pnAMzmgzRg1ie5Pdmy03NIRaOk5YZ7P4Q81uUq0Vq/w=,tag:GzoPdk6uPblm0LAY7rdk7A==,type:comment]
    #ENC[AES256_GCM,data:+AvyN0uDFs9Erg==,iv:Q/EfOBPn8N6vtLt4RAhXgreJ/CIEoaV5zb0k4hi8koA=,tag:xJ/lVI2G3JnBx7hHSWLSQw==,type:comment]
    #ENC[AES256_GCM,data:PesmR0mD+IwqbtxwRIzqRbaPghuWeyUqb5yoBXj0gcNQ4QIrEHoxDIdfYftsPaDix/o=,iv:f1J9qk/t9R+Ksnce7swUw15WCm2erz2aC6444bafwUQ=,tag:K6b9/huloZz0ACyQWK4ZSQ==,type:comment]
    #ENC[AES256_GCM,data:+yOc45nKzOudyGXYA8AcAbIBAG66/I1FVwkxXGU2CfQSpT62YChtSGK1Oma6nSF3L8UW,iv:wVYsPRFPKNs+Z4UTnYYfIaHfnB19gp54lLpGapXWimo=,tag:NBZo6Iy58H4gWW2Hki3ZRg==,type:comment]
    cloud: ENC[AES256_GCM,data:iS9XElv8YpRFfE5taMbz8u3eI7LnMNavz+MLFyyBgRk57QQ703j5HHH0kNmOLtFhD6FS2VPY3Rt7akw0ZPgmBDfmGiI8+/8eDvVhDlrdaUM6OJcmplDo59lPr3ZVMpbmfDzPh/mDtkmGTOZJ,iv:3669/DlAwyNRf4+WXiup0IjxUaYCU4lDPuqEQwD/V5c=,tag:+SNkiq8ndVL61Rc1yuFj/w==,type:str]
sops:
    age:
        - recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVWk1VEN1eVNQbHY2V2Iz
            M09BbUJZaDhVNUpsTyt4OWhRdGtFM3cvd0NZCnR6U3NSUjJIU2t3OUk0QVVIZFl3
            VTVHSDBFc2trQjFZSlluZTB1OUVRajAKLS0tIFl6SHRtUjBxOHBWTG1abGhWZ0Yy
            WVRxcC8wRDJzNmlXbDkwaXFGa0hLL2cKqsE6l8Q4nw0s0I//G2WYY6SgdAgC3661
            lY7yUEXUr50PPJTTMQEvPUCOczL6tVXN7gIhJ59tY4BkBNVPnDIneg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T03:12:17Z"
    mac: ENC[AES256_GCM,data:+5eEde9FnCWU1s+8Ukn9lAeYQYDt+qUiv/n/cLnYCPEYrVmCS6iurBb3ueYn3XL1Kw77aT2GvAkhczSZKlUmEOmgbh35bhZidHSpBZEJebAO2SwCcD1hBw7u47gM4qHmbsQIaeLyGn5u7+LHhlkgpiUbzTdCf27lddOoj7ZDTjU=,iv:isbvkQjyEaNpBERjJAFeLfOXykd2wkqOnCCDFrCMjnw=,tag:xXpP9lCDqpQs3h4E7Wbpzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
