image:
  repository: velero/velero
  tag: v1.12.1

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      config:
        s3Url: https://s3.us-west-004.backblazeb2.com
        insecureSkipTLSVerify: "false"
        s3ForcePathStyle: "true"
      credential:
        name: velero-credentials
        key: cloud
  volumeSnapshotLocation:
    - name: default
      provider: csi

metrics:
  enabled: true

nodeAgent:
  enabled: true

nodeSelector: {}

tolerations: []

resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi
