apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:uDcZFr3fMvKLfWfVQVH0t6iY1kHKHJl40tSZ1paUyCI=,iv:3W9Rm/GNRdBihDSnx8CXJQVZP+pWDhicbq3IIQx/sVQ=,tag:EVE08LSsB5gV741cPLfxYg==,type:str]
sops:
    age:
        - recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBREVzRk1xc1pRTlNZSSs3
            eTNmNjVnZjV1aGFIL3RiTGF5eEMrcVMwQ2hJCnJaUTQwUnFPQ2Vndm9SN0tGdjM1
            ZU9oNXZjd1VDZE9xcHg5WlBjVTlNUUEKLS0tIGo3RU9FSmk4dzJEWEUwYzhXWmxC
            T04rR1J0MDh1b3M1K3hXb09ndmJCcW8KksKHjrGvgEdZIpIFcrHJXQsoj17emGwv
            +2MM1/ZPVgfKz904n4dBSk1sU/pll2PDrPbSr5cItPQV4kVrIMk3cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:34:31Z"
    mac: ENC[AES256_GCM,data:2JRwH8URWMX1FCKBt3m/qA83bTdfyZMXJddxOr/PP1bGjyYNDHt2MZ6oGRa0SJaxHdK04baZkXwf/ejNj7DIq56BAuoQv/Wyv+ZV+K4xX5mmR1hBwWt7ZhqEXguUT5c26OdKJl9E9rxEVyTwkze3sTU01X31YAQx9Z5QOnNDwEc=,iv:G3sTD2+j1FuzhPImNUZLgLbKoTUhFsVYLYQhRRspDwA=,tag:pWSkDFKj7Ey9wVSJT+W8Pg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
