apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  labels:
    app: postgres
    pool: private
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app: postgres
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
