apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ../../../../apps/frigate
  - pvc-config.yaml
  - pv-media-nfs.yaml
patches:
  - path: service-dualstack-patch.yaml
  - path: deployment-hw-patch.yaml
