apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared
resources:
  - vaultwarden-http-redirect-httproute.yaml
  - vaultwarden-httproute.yaml
  - immich-http-redirect-httproute.yaml
  - immich-httproute.yaml
  - llamacpp-http-redirect-httproute.yaml
  - llamacpp-httproute.yaml
