apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      version: "v1.19.3" # Use your preferred version
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: rook-ceph
  interval: 1h
  install:
    createNamespace: true
  values:
    operatorNamespace: rook-ceph
    cephClusterSpec:
      network:
        provider: host
        addressFamily: ipv6
      storage:
        useAllNodes: true
        useAllDevices: true