apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared
resources:
  - ../../../../apps/vaultwarden
  - configmap.yaml
  - secret.yaml
patches:
  - path: service-dualstack-patch.yaml
  - path: pvc-storageclass-patch.yaml
images:
  - name: ghcr.io/dani-garcia/vaultwarden
    newTag: 1.37.2 # {"$imagepolicy":"shared:vaultwarden:tag"}
