apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: shared

namespace: shared

resources:
  - ../../../../apps/vaultwarden
  - configmap.yaml
  - secret.yaml

patches:
  - path: pvc-patch.yaml
    target:
      version: v1
      kind: PersistentVolumeClaim
      name: vaultwarden-data

labels:
  - pairs:
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/instance: magi
    includeSelectors: true
