apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:FR9oFTxDPD688Sd+82SWIjAe0j2/T0CnA+wunv0mRe6/B4LctBLPQ/5QJg4GA3phEDIGrvwIfbaArXnWPJ7B1aEaodjezGBvtmQLImSCxJmpl9v4KUQiBSJdJ8Jh5YomWiwiZ+rrW192RFkZKxTZGdw=,iv:prLlLP1ujDdifvF6bPWib5eQgy4K7mOq9ixPPbn6RPQ=,tag:NG7zeKYVK1bi7NHVkvyAVA==,type:str]
sops:
    age:
        - recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aTF2c1RkTS9UQmNHQ2V1
            emNxSDN0OW55OWZyV285TDh1VGx1MFhzSUMwCjdWQlg2MFFkL25kVHM4SGhhZjhI
            ajczcTRmUThqUVBRQnA4VUg5NHZUYUkKLS0tIFlvckh3SUlJOHF1R250NUNPSjdY
            U2JsV0ZsWC9RSXRKZWxWRzByczVGWEEKLdw3iDdXF1QcIvkd38zXw2m9UQ+/7Fnd
            94e1WginqzulpcAm4a3ZmyfXHmZaQx2L/wYc2s1VdejPw4DsDaAI7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T02:47:22Z"
    mac: ENC[AES256_GCM,data:V5sKYuQ8bOfZeILcch7KdsXt4W4F+wDyBy416ztJhFg/55Epd8uIG9R9UBtTL5LUJxk+3vKUZi2JEBZ8oT2kIL39al8+1Rks68lX54YifyurT5NiAFAwmQhOMek8YZ887LH5lunyZrEnl7pGikW0w8ofKfrGttbaLgXz8vtXZ/o=,iv:ZKeeml/zM32lWkQ5hShpVGIgadDQ3OzqkhwPjDq3z6o=,tag:kwJDWwui3m9w1eK4pKGhbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
