apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: home
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:uYt0shzqdYwQd/mOuUHwF1c=,iv:zFsPXKXV67NNIeyyR7Cy45EPbXEAAMQhzeluSjc7cJo=,tag:VTAtsHtdXM1UTyS3sAsSAQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:xQ+eFiYQDveZQD+cyylqa/YEX08tNow/wES9Qg==,iv:gN9aOIhQk+B94JONl6CXtoomiLfYEqxWkUEQ2RoOWOI=,tag:ZXjqAtyeui6mwJSpz3nZgQ==,type:str]
sops:
    age:
        - recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTTBoMm1xV2NuQUdwYVd1
            Q0w1eHRrZ1dKN05ZNWtvYmdDSW5EK3dmS3g0CkJEd09TTWk5d2xJdkRma1MrSGxo
            Z3phRlBVTHpTYWg5b25UQzZ5dmhyK00KLS0tIEoydmNvZS91QkNqTVFCWit6N28x
            WEEwWEpJaWt3SDBzVlFOVEF2MHJVRlEK+I7WVWovqcNYeAkEExtKCXLcaeYMnxu0
            ny18xvhhpiYL8aAiJNHUe9QFoouBs0ChdjxQ5TNQN7/PSznrNa5yrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T22:31:32Z"
    mac: ENC[AES256_GCM,data:j5DVkCYvjIPeduroWkQBSfF56VqXjUFS3h551JU6SWBhcBjyopGuJxvkftQX7dk1OfW1rQdWjR4dccw18yVeyyTL2PbdCZA+Kpt5kVWbJRE1ts8hY0mUrp2QhSSIq9yuKlxoKVrKPCIG9WG2tGPwkHK5E/42yGhGvu8hCiPsjaI=,iv:jR7z3Bb6PntFV9l0cbmRQpfyQ7AvTouimLhS9zIBy8M=,tag:PxQt9mUW7/KSl7aYQc+YBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
