apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: shared
type: Opaque
stringData:
    ADMIN_TOKEN: D0k8Pd{pA9^|}F32j
    DB_PASSWORD: FNqfY32jB5BvJ4NYxxV/DzSZW60v
    DATABASE_URL: postgresql://home_vaultwarden:FNqfY32jB5BvJ4NYxxV%2FDzSZW60v@postgres.databases.svc.cluster.local:5432/home_vaultwarden
