apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Install Kubernetes Gateway API CRDs (v1.0.0)
# Required by Cilium Gateway API functionality
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.0/standard-install.yaml
