apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:aJMZ7NbwnVDXYnNKoYwCPd6XkCzFDeE64IHRrNlWDV5i1AXVxkpJwpIjmZlHnIn43RfDGBZpmOjKjRRioC9n93kjcIBc8V0kaV2A00WNcxfwqIpxxR56nwSlVq5N/JuAN3PNyC9ZnNbBnPnkSbqWzLxwTuuLAGWs9RAPcSdszrScEyT5ueP2bvf/rsWHmfWeIBvEr6MO/Xb5GqN8Vr/hcJMC7rSXV38q,iv:4FABJnJ/HFzZXCjkj3P4AVt8hO0CQfgmpQWD4VyNfJ0=,tag:i6fgK4xQetQV8Q0CK/V4gQ==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: verdesumergido
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQUdScDFTVlRuTjlWYmV5
            OTA2ZGhGdVJmdThJNGZwK3k0alRxMjl6TVM0Ckp3VzlMOXJqbkVvSzY2dm0wR0pT
            MUlOZ0hCeVlPODJqendWcWxYd1E4R0kKLS0tIGxPZGgxdExTcmg5cyt1ZllWajJP
            SUNSRTU0djBQbnJ4ZTFtR1JjU3hkczgK+AqVtpMS9bgp4czrAZ3FCbgKARGvmePf
            F3lr27rESrgIWp4c8jthCpw1Awavpj5H0CCGrqeFE7pE5fVFe18GGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T05:41:12Z"
    mac: ENC[AES256_GCM,data:tncsDNo6yXfkEP1K3IZAuExgSeHb32ur37BJlNaVKN/eBkydIAF2wQMT9DPC/ZJn/T1+5YSvtMnbE4sHSU3UPKjlr9Yy3oTNC/esGiL7EysLhvUYkukruQ6UBrWD57NHiWOYB5XDGCalghCqQCkeFlWOezR6UFsn91lG7/in7xc=,iv:m3hUqlHQLrOc7urRqQZXKGBpyElIBAzpV56YWTs6kfg=,tag:6QiZvLsQ7xCj2OzsVdnNYg==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
