apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: verdesumergido
resources:
  - namespace.yaml
  - ghcr-secret.yaml
  - gateway.yaml
  - certificate.yaml
  - ../../../apps/verdesumergido
  - secret.yaml
  - verdesumergido-image-automation.yaml
  - routes
images:
  - name: ghcr.io/vbalexr/verdesumergido-api
    newTag: 20260725-0010 # {"$imagepolicy":"verdesumergido:verdesumergido-api:tag"}
  - name: ghcr.io/vbalexr/verdesumergido-app
    newTag: 20260725-0010 # {"$imagepolicy":"verdesumergido:verdesumergido-app:tag"}
