apiVersion: v1
kind: Secret
metadata:
    name: verdesumergido-secret
    labels:
        app: verdesumergido
type: Opaque
stringData:
    NODE_ENV: ENC[AES256_GCM,data:OUYNwhHpnS03wQ==,iv:qVkdg6oEp0ICLsaqrYXzHCUKp/KpuL35oJFUBmZWEi0=,tag:jrmsW5R3/qf/OHYaiRAzbQ==,type:str]
    PORT: ENC[AES256_GCM,data:nizxng==,iv:7C/HA50ntN+IM9vSvds00HjReiy6dVUssSLPnFbXdY0=,tag:zI/iSOtzy5qymEL2fEvsfQ==,type:str]
    DB_CLIENT: ENC[AES256_GCM,data:1ndJum5Fezs=,iv:lUCCPhoSAFfUBedzUQtgcN/stK/yZkK0XdiYEYnolsA=,tag:Eqk+U0WNMxL9IIs0rUxPhg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:dQrYDuU+fINMIt8ARI1X1f4CEmUGAuJCtRv1m32XnmjE6drMtv3lhsoG+3SZW839IFzzJAdgkxXyIffttjEB8siAzEz3kCaDiXp0uKEvAsxA25xEKOOULQhVIOl7KRxHCshuddv7xw==,iv:6ETr9IfO9s2HESS/TWWjSAswvY4OhbodRUEMtfo2KxY=,tag:Pqnib1fhFQc6RywJXtg7EQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJR3dKK0NqRVNBMFRGV3Jk
            UjRVaWVwWENHM3Z0N0JLZFZFNm9ZL3BJNlRRClJPRWhHSmJ0eExnL3lMcnRqeFRo
            QitFNllzMTBTZ1Zlc29iNGZ6elNUNVUKLS0tIG9VampIV3EwdG9aR1ovYlFVemJ1
            T1o3NStYWHRSd0JUb0FRVmlqLzhHdHMKP45e2Ps0/3qsUZr/16KTilvV/chv2e22
            EzVYgBTBKidLPXgO+qRsBR86D3fhrSUdtKm2pYZhkgvp6bZw8pepZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T05:26:16Z"
    mac: ENC[AES256_GCM,data:mxcSLGxH+411julBWYo+qHey//VokHdkAuC5cYaF+54mO4hPQtW5vzfZzuCHVBL2j1WMyO59cSIa5Ns3zhzzmyhBCswK+5bqW+lLUkpDDc3sGBN3C799Rud2ysDbqOFQzTqwlpIl/KlzgRk3jGvDKTD6IhAlkz09MBFSqxAHD14=,iv:jfh8cOgDYeLXacJN2vplpk36YScae47t7dDlihdhyjM=,tag:AJh7aBltiRvTR55gn2wwfQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
