pid /tmp/nginx.pid;

events {}
http {
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path        /tmp/proxy_temp;
    fastcgi_temp_path      /tmp/fastcgi_temp;
    uwsgi_temp_path        /tmp/uwsgi_temp;
    scgi_temp_path         /tmp/scgi_temp;

    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    server {
        listen 8080;
        location = /favicon.ico { access_log off; log_not_found off; }
        location /static {
            alias /var/www/myauth/static;
            autoindex off;
        }

        location /robots.txt {
            alias /var/www/myauth/static/robots.txt;
        }

        location / {
            proxy_pass http://aa-sspti-gunicorn:8000;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header  X-Real-IP   $remote_addr;
            proxy_redirect off;
        }
    }
}
