apiVersion: v1
kind: Service
metadata:
  name: immich
  labels:
    app: immich
    component: server
spec:
  type: ClusterIP
  ports:
    - port: 2283
      targetPort: 2283
      protocol: TCP
      name: http
  selector:
    app: immich
    component: server
