apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  labels:
    app: immich
    component: machine-learning
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
      name: http
  selector:
    app: immich
    component: machine-learning
