apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared
resources:
  - namespace.yaml
  - gateway.yaml
  - certificate.yaml
  - immich-image-automation.yaml
  - vaultwarden-image-automation.yaml
  - vaultwarden
  - immich
  - llamacpp
  - routes
