---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: vaultwarden
  namespace: shared
spec:
  image: ghcr.io/dani-garcia/vaultwarden
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: vaultwarden
  namespace: shared
spec:
  imageRepositoryRef:
    name: vaultwarden
  policy:
    semver:
      range: ">=1.36.0 <2.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: vaultwarden
  namespace: shared
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "chore(images): update vaultwarden image"
    push:
      branch: main
  update:
    path: ./
    strategy: Setters
