apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./infrastructure.yaml
  - ./databases.yaml
  - ./verdesumergido.yaml
  - ./home.yaml
  - ./shared.yaml
  - ./sspti.yaml
  - ./configurations.yaml
  - ./tunnels.yaml
  - ./mrakaki.yaml
  - ./monitoring.yaml
  - ./chilu.yaml
