apiVersion: v1
kind: Service
metadata:
  name: aa-sspti-nginx
  labels:
    app: aa-sspti-nginx
spec:
  type: ClusterIP
  selector:
    app: aa-sspti-nginx
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aa-sspti-nginx
  labels:
    app: aa-sspti-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aa-sspti-nginx
  template:
    metadata:
      labels:
        app: aa-sspti-nginx
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: aa-sspti-nginx
          image: ghcr.io/vbalexr/aa-sspti-nginx:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 101
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: static-volume
              mountPath: /var/www/myauth/static
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: aa-sspti-static
