apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aa-sspti-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aa-sspti-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-filesystem
