apiVersion: apps/v1
kind: Deployment
metadata:
  name: aa-sspti-worker
  labels:
    app: aa-sspti-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aa-sspti-worker
  template:
    metadata:
      labels:
        app: aa-sspti-worker
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: aa-sspti-worker
          image: ghcr.io/vbalexr/aa-sspti-worker:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 61000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          command: ["celery", "-A", "myauth", "worker", "--pool=threads", "--concurrency=5", "-n", "worker_%n"]
          workingDir: /home/allianceauth/myauth/
          envFrom:
            - secretRef:
                name: aa-sspti-secret
            - configMapRef:
                name: aa-sspti-env
          volumeMounts:
            - name: app-config
              mountPath: /home/allianceauth/myauth/myauth/settings/local.py
              subPath: local.py
            - name: app-config
              mountPath: /home/allianceauth/myauth/myauth/celery.py
              subPath: celery.py
            - name: app-config
              mountPath: /home/allianceauth/myauth/myauth/urls.py
              subPath: urls.py
      volumes:
        - name: app-config
          persistentVolumeClaim:
            claimName: aa-sspti-config
