apiVersion: v1
kind: Secret
metadata:
    name: valkey-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:xooxqlbwcu5gm24=,iv:FNqfY32jB5BvJ4NYxxV/DzSZW60vk57eiJPZ9XLQoXk=,tag:l6WDJaEnfx55aWoAN6+B8Q==,type:str]
sops:
    age:
        - recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMR2FaMFlXMmtiWDJKV1l3
            YWVzWnhrbGRZa1dyeDhJZW5tcTBBVWM2aTBVCnZCcC9QSEI1WGxEbm9EVHJMTzZ0
            UmFZeGJuSnpGTFl2MURkclVMcENmS3MKLS0tIDhxS3FxdldsTFFBdC9UeHEzSWlr
            cHR2ZFprOHc0ZFA0RVZDMHNZQmdUdDgKIVFcuXAla+YFiRMNykUXio9gkf27a/lx
            lkN4tsRq8tP5hwB4tq+7z6snXBmPpElLHZOZH3PKULl1Vbg0VUvJsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T17:16:47Z"
    mac: ENC[AES256_GCM,data:0oTmqglQ5Pr9UWFPcLvLR5PxZJ/hkYQLz6khPGl8kHhqF3bzqovFwR9EKK+C6YDoukFO3IwaLZacYf3oV1u3343TQ97oeRjiWNOLX8fZ0ddi/bQerEVANWYgZep8jwHvg0yAXsm+vkGswER/LVxpGTqLE+WYdV555JiATUCu0Rg=,iv:gFWXaR+WpVMQY1Vc77oZ2ZxkZ2eBS4DeFeJmJXRha4w=,tag:p7AXd6Otjfiwud3sM/G4tA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
