apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lh-fast-block
  resources:
    requests:
      storage: 20Gi
