apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../apps/postgres
  - secret.yaml

patches:
  - path: statefulset-patch.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: postgres
  - path: service-patch.yaml
    target:
      version: v1
      kind: Service
      name: postgres
  - path: service-headless-patch.yaml
    target:
      version: v1
      kind: Service
      name: postgres-headless

