apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:3SNKQr+WaRMsTZAysNI6z98W,iv:zgpVKD0lji378dx555JwZL9mFLjk1Q6a/MZWgUF4tDg=,tag:N1PJANKdYrPYRjefcvZV2Q==,type:str]
    username: ENC[AES256_GCM,data:gEqPPuaGvWo=,iv:0k6mo4VwErQLS3OXhtauelrDdRqqb+KDDSpSkRS1F8s=,tag:+U7ptWpzbcjjFtj9AZEfJw==,type:str]
sops:
    age:
        - recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMVN3Mi9CdXVzam9oaUY3
            c09RK08rUjBwNTUxMCtGTTd6T2FJMlBEaXp3CmxNaGFUbElKV1JoS0VnMFIwelJ5
            OG5ibFMzKzV3S2FYY3pTRlpYYk5VbzAKLS0tIENvU0FnOTZwNTU2RU1aRDNOaWhJ
            TnJDekI3K1JaenJJRXMrRHNtaGlPVmcKuRldsaO8sQBzHPLCEPQ6DqNA5CjEMYzv
            sQ+nDwUYFIuPNOR5R8mCQvupSu8ZmtN/CvZAy19ZU5PNG7A7wxlDbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T16:13:25Z"
    mac: ENC[AES256_GCM,data:h9kjmV/Lf7b5VMLC5k1tKVFz3qUHrRTy88y0dKsd2mDdqdGA/UHyjNKix+SNgQckng8RPiW1q5Zh/PAQT66sWt2YRKV+RMMHxEo8+XXV6dEKskoDVAGGaZU72rI3CBLhwLXhNKZH1jF4hgodsfQjIXQ9YplkgY+3QT9595Cqy4U=,iv:A9ZLOKeqoxEd8VWTazn4DctEJiY9zWCUkGA6B1XU6IY=,tag:8nDGsSB4slhe9TwCIurmHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
