apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: postgres
        image: ghcr.io/vbalexr/postgres:20260421.1510
        args:
          - -c
          - shared_preload_libraries=vector,vchord
        resources:
          requests:
            cpu: 2
            memory: 8Gi
          limits:
            cpu: 2
            memory: 8Gi
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ceph-block
      resources:
        requests:
          storage: 50Gi
