apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  type: ClusterIP
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
    - name: mqtt-ws
      port: 9001
      targetPort: mqtt-ws
      protocol: TCP
    - name: mqtt-tls
      port: 8883
      targetPort: mqtt-tls
      protocol: TCP
    - name: mqtt-wss
      port: 9002
      targetPort: mqtt-wss
      protocol: TCP
  selector:
    app: mosquitto
