apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: home
type: Opaque
stringData:
    #ENC[AES256_GCM,data:vT94BDngObbhTpFTnce6606OYGg=,iv:C+PlzR02jFkGWwG9B35Wmee30a4ngD2MJRo3rITc4r8=,tag:VL6BXHZ7H58feJByek5j8Q==,type:comment]
    DB_HOSTNAME: ENC[AES256_GCM,data:NGAFk/6RQ2BXSX/1tGhKxTva01suF9A6LOq0Gm8V8HvZcZhb,iv:G+FdPtym4BxPBWN7m/x3nA+GE5LrKt8wP4ZOB5vOELM=,tag:IrcsF9/eo8J/vcryNpAI/g==,type:str]
    DB_PORT: ENC[AES256_GCM,data:zalt4w==,iv:/lBRbVqN3TjKmQ2g16IdSacaZdw27bitXJUXt9jxkBM=,tag:J0OrIkC+61ojDTQ2OIPDMw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:rUB4O0pTtqC5jk4=,iv:N4Qo5Vr0+b4X61X2Cdc/HG0aZFGuYv6M4wTX3rOxn74=,tag:CqFivO43YIkqfO9dJIK/4Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:M4ospUz9Ia5KyE8sgCh9,iv:W1SZbat2Rt0QfsfDfx6gplkCQkIrMJY1oMK2Ix8x8RQ=,tag:BBpF/i0t5NlNaIJywRUNow==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:FHVI5kEEInDImg4=,iv:MBEVuop62WLDy9ONaNrU6vd/21u4QBUx+9bVwJ1hEsQ=,tag:WWRSlnYxA57joHyIoRhT5g==,type:str]
    #ENC[AES256_GCM,data:yScYqQ+7wrppD+zykNltxseB6ZMXYiWw,iv:LV70Ga/z7P+mY5d4ORjwDbfXOP3Epnvj+WpiyUipC54=,tag:xSmSPR0UuNJqfG/9dOtjUA==,type:comment]
    REDIS_HOSTNAME: ENC[AES256_GCM,data:C0k21IT+3hP/HHoeHgtbpwi28rGzFJYhZVz+4aJnGxFNZQ==,iv:IFeNYTs76wdCdSASwmdViz/MMnjuhIDqkzatlE6s7MM=,tag:+pfmUYPM6sA9lGe+GoOLGA==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:f57tSw==,iv:x/7tVjOgaKIlNrZl0oWhr/xzbv6vzyCQUip31tY+tnQ=,tag:imFFpvFXp6FDM6mr09tfTA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:E0oRrHgq2Od2a5I=,iv:UP/DLeWONZnDO19xhwsh8LkmuNgPcz49kL+CFNAuGzM=,tag:BufVlxY2g5emCzkRGqVNsg==,type:str]
    REDIS_DBINDEX: ENC[AES256_GCM,data:Ug==,iv:if9UvDrRd7yZVxXtx812MlB02mkz7kUssh5HibB8U1A=,tag:rLYxWTtJv2zkxnQ/ph7t1A==,type:str]
    #ENC[AES256_GCM,data:khVMXxMU1fiFNVI2l6SEAy0=,iv:JyLmLBeGKI4fqEPmXt1xyYDqT/9LoHLUSH0+AflUpHQ=,tag:oNjRxX7u5gjP6pgpieRrXg==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:V/f4X1kHjUT0kpptGuhkmd5GcOcPNEyzIWdSYpyVgA==,iv:wioIGSgI8pSTJZF05u3oYo10udloWBIF5Tl0XA3qY2k=,tag:l+PN4dgS+oue9zeYxSpBbg==,type:str]
    #ENC[AES256_GCM,data:0ZVG7R8VvYehsBJtEAJrhCfsSCM7,iv:cX38BqEIvPV5guHyfAVJdtImGx9djQtjFP5lYJtJnlw=,tag:MJYciTER1muvRlTj1FHFFA==,type:comment]
    UPLOAD_LOCATION: ENC[AES256_GCM,data:LQx5r+Q=,iv:PheEpn5DSsoc9N81HvfEKvPspS+CuMyYMC9bwHI+ZSU=,tag:ariYWFzToLHANBlrpYY03g==,type:str]
sops:
    age:
        - recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSUlwSGFMOFhwZ1JyU1pQ
            UkhtcnpIRVBGamF0S2VJeHlZSmRxalJISzBvCmVZdWVPc01weml6ZnVoMkZoY1J6
            T2ErdjlYNjlqZ2t1dndUbDdDL2x6c2sKLS0tIGk0cXBhVk5KWGJjN2xjQmNheEFC
            cHNEZ2VtM3UyaWJReTE2TEFQMURkdkEKJBSYhzh6JBw8dRlllMmn/FIgvqoB/tjP
            o53v07kjvJmotx8Rl3LPUUUiOLJyOVuFC4eNYkrgDZxhJef3y9xgDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T18:04:17Z"
    mac: ENC[AES256_GCM,data:4fq0bMOO58tXu1wHweYIn29SobaPKN0VnmpY29iQ6USDYBNkZ77xEcHCL9yZ7yb3ZmQxPn/41mTVJCDZLak/hjCWSbVd5ufNqJREWTlMqIib6xJElUL7tPVhSwL9+74fDX6hqojYt3aHhc0XSc7JZ/2Dhp4n8AURIZkGZy7CiWM=,iv:mNkMLkVPpB6Ni+GW77njdIhXq//FgircZK3zRw6m/tM=,tag:kTtgpVxoCBiwNCwIN/muGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
