apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:k1II27A=,iv:1gYYFFOmXQWrVuJQs4Js/bSnGn0hHJnNaPpQJ7q0vqA=,tag:ZeQHMBK1CqvpJPbhnTwG+g==,type:str]
    admin-password: ENC[AES256_GCM,data:4G6+ZdNmxEyNml3aGiB/6LGBrA26BiHsU+rRCP3itPg=,iv:WVGDdpmEp2HK1KKteIxqgYzgc4f8gDV4CejNR0L7hYY=,tag:/ogCfzDyEbnxlerFK2ihdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVHQ2a3NPSCtRekVLc3cw
            a2VZK1BTUW9QM2ZwOVNwbGdvcTAwWTd2ZUJnCkVaVGRXV0o5Q284UnUxd1dybldt
            aGplTXVUdXFBc1ZhcnVBUmIzNGU2L0UKLS0tIGI5c2w3QWxCTGdlaC92OGliZUlF
            UDlFUUlyYllVdUtqRnBKYm0ra0hkSTgK/QJsEnofgU/U+jvkbYKHoPtgnC9mDg1b
            0+BPY5WsD6N3Dlq7POAsYrKEtG2J/NNcba+WqTzusbZWfgVzQPqJ2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T01:39:07Z"
    mac: ENC[AES256_GCM,data:ScJZNJXtTgm1lzRHv5wWUkIooUbarJ3LoF/t8IiN4MS1WejMTN/K1dWpTHEMXzTvV30K0iUO7au9H/cz3HY9ecmxvLbz4/mvBNMeomxOqNmnaqODChR+2f3dhZ7U8X9+iKSvx+ciqcF2XTNHfi9w23LyY7d3lW9Ao0/+EOmbdw0=,iv:Ja+t7JShzy3QGuZFHCaMcPDwAoIqrGm4DQhpyG8MNZI=,tag:M7iia7+9+H9lK3mwcZl49g==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
