apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
type: Opaque
stringData:
    webhook-url: ENC[AES256_GCM,data:ReeVfBOjsPXNZrJ3paKgq1eI4nwWTLCRDIw7v7XegahKXxKsx2+xrSdBEbUtSxfAFlq2MV+/3gwd0EE7xwspbdUlXjAU89pK0/uoAGPyfZ+zdl6ku/CvgUN/a5wzdxA3Iss8ZCytSyR40VNfeX0FJP6gShHXcuAz1lQOMA==,iv:DrzchKath0SHVxVxXVehUxzBR5/TD1Qsg/5S/Ake4RA=,tag:Gpu1VK5RZdMmvdX1dZaIYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCM2xuMXB0aXl4T2s1Y3dF
            T1Vici91VldIRzFHMW1sQ3pMUkZqaWxGL3pFCkM0UDNQVUE3NVkyQ1pld3JTU3JC
            N2tkVUk5SUJBdDI3Ykl6MS9MUWJFNnMKLS0tIDNUa1hoYzdwd1NHZm1CRVFvcktl
            VmQ4ek5LbEZGSWFuNERFUEN0Q2lraVkKok70lRdN4IYdKzGpMigxPukfys+eARi3
            itLAn3QjgM6J7MN7HDri1KC3UKbp1vWJ/d5l2Wrio3cv0u8h87Yr3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T01:39:07Z"
    mac: ENC[AES256_GCM,data:FmZZsjyZylljIyuHPfHsmnTVX4r4EOJrdbVk2v3a9ha5SqROdDGrJmoK2GT3UKvK085BVWzN80E8shdxXf5ZpOTTcZ2o6nY2XtNWjRztx9mATbBOT+KPy+syp9NV4X8Rl0edA+Gy0e4BkF+UPmL1pliK1UfGLi/s82TYisMHgN4=,iv:z15lb8SLTcSt2X79qDvjY2BgFRdpJlRXXx5AFjAfvEc=,tag:JlnI8Sg9NKRLVhAMQncCUA==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
