apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-initdb.yaml
  - configmap-config.yaml
  - service.yaml
  - service-headless.yaml
  - statefulset.yaml

images:
  - name: postgres
    newName: ghcr.io/vbalexr/postgres
    newTag: latest

replicas:
  - name: postgres
    count: 1
