apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared
resources:
  - ../../../../apps/llamacpp
  - pvc-model-cache.yaml
patches:
  - path: service-dualstack-patch.yaml
  - target:
      version: v1
      kind: Deployment
      name: llamacpp
    path: deployment-model-cache-pvc-json-patch.yaml
