apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llamacpp-model-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lh-slow-block
  resources:
    requests:
      storage: 15Gi
