# ./kustomize/bug-patch.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
  labels:
    tier: node
    app: multus
    name: multus
spec:
  template:
    spec:
      initContainers:
        - name: install-multus-binary
          image: ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot-thick
          command:
            - "/usr/src/multus-cni/bin/install_multus"
            - "-d"
            - "/host/opt/cni/bin"
            - "-t"
            - "thick"
      containers:
        # Increase resource limits to prevent OOM issues
        - name: kube-multus
          resources:
            limits:
              cpu: 300m
              memory: 150Mi
            requests:
              cpu: 200m
              memory: 100Mi
