apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ui-gateway.yaml
  - pvc-ui-uploads.yaml
  - auth-service.yaml
  - process-service.yaml
  - inventory-service.yaml
  - production-service.yaml
  - search-service.yaml
  - notification-service.yaml
