apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tunnels
resources:
  - ../../../../apps/cloudflared
  - secret.yaml
images:
  - name: cloudflare/cloudflared
    newTag: 2026.6.1 # {"$imagepolicy":"tunnels:cloudflared:tag"}
