apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel-token
    namespace: tunnels
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:UrBNDs6BwCbzRLJU0EFdPy6sDafm7tfig+vkBqZabx07UBnrQd5tIOgSK+G/FHG6Ww4+g25qPyQYrp/mFTQcE/rau31IJJtEWgKyIRx2r4/Bxl6cphKeeUjfunZudk+9URf8I0Kln0ISTf4mxVK7+aUyrGCZdQ+9aVMF4/JZJjUNsMEImvi8MyUHtL+0hh+us3RhFhAmJX7nzjJPjGcdPy9e2utzUPLfrfhKxoFjAglZxsx/MhsVXQ==,iv:mrbDa7lQ3JEYFT0H6Ud4khzep2yppSz7EJ0bBhnc6vk=,tag:2ll05b7prKE+YDZIhv1Y3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhckdzNmI5d1h2eDdVSXNE
            SlNkdHJPRVhzTG5GaXo1Mkg5TVRYYmxYWXpnCm8zSDVNYTkreWoxeGNGUzBkcTBY
            VEdDeEZTcU9WT1VHb3ovWE0ySXppUUkKLS0tIG5hK0ZJejVaMVFzc2lwYTN2eXJD
            eHpNZXVYV01GeExMU3oxRWFWaUhNM00KIJYP5v2qdNdg5caKYXhbe+r90xGFtWt0
            Kx1ARqKvONY/Mht7zShFRP6C2VWZAMSIB5juFnjsDjtWpI7dm2c7/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T05:07:52Z"
    mac: ENC[AES256_GCM,data:pQ57Ob3Qeau2mFHNATkWbtD07+aSURDO7CxHCuDcfZHTHaAub/YGzHhQ/jMsIRAUND8ucCF1tbtV9Hk5Lhh68ehA8MFRy0G+uoe/OozBFM+lhdsB/wOSkhEyKaMQKAaU/2nqa2rQ9U9vHe6QccAACGhWNArZJef/iLfPNl/YRP8=,iv:nkNnQRRDcVbC7gVzDb9tXiU05aOZy1QVTfQyqY62Bqg=,tag:6FFkygCXEslshJmTyN4cOA==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
