apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chilu
resources:
  - namespace.yaml
  - ghcr-secret.yaml
  - image-automation.yaml
  - ../../../apps/chilu-bb
images:
  - name: ghcr.io/thegamerytofficel-blip/buyback
    newTag: 20260727-1934 # {"$imagepolicy": "chilu:chilu-bb:tag"}
