apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: home
  namespace: home

namespace: home

resources:
  - ../../../../apps/mosquitto
  - certificate.yaml
  - secret-users.yaml
  - pvc.yaml

patches:
  - path: configmap-mosquitto-patch.yaml
    target:
      kind: ConfigMap
      name: mosquitto-config
  - path: service-patch.yaml
    target:
      kind: Service
      name: mosquitto
  - target:
      kind: Deployment
      name: mosquitto
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: mosquitto-tls
          secret:
            secretName: mosquitto-tls
            defaultMode: 420
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: mosquitto-tls
          mountPath: /mosquitto/certs
          readOnly: true

labels:
  - pairs:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/instance: magi
    includeSelectors: true
