apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-users
type: Opaque
stringData:
    passwd: ENC[AES256_GCM,data:ifkT/iOBPIQPJUvzUpCJjM2vvMrtrGwPy0ZhlESyJmMSxj3uUjbJ3mmVKKdkBkgLx2m1kpA5eeIKDXzpRpwtS43bM/obU5atrAnxqN6iEoweYspvv/botRTSJ2m+Zkr1x96YGcL9Q4zlgKlUmUwarEHrlpQizrkR1Kzq7CiqVE9nD5j5KLXR/e42ZzZKr/6JP4463gGnAvHIFxHgMxYwukRseoRlw1l+wh8MyN53tEEx+rX2wmCb0i03d6NRDVTU5T7CP7xp/87m8HinUwtziiOn9wv/hyw+JWwX4wQJ0IxIDPXzwakODLBu8aE3PyCdib2n9o/uIG7N6vgEPYTEvTDvF9JG8AySYTv/2jnWGes0gtDTOOjygaAS3P1bdWIfxbZj1JETbFYYABkc5zp4YpwsB+IHC6EUhemxf49ujgqH+AgnEBFWAF3pR2EnMMQAtLWopEeZNkD4f6IndFmJXlUOuVtFAQRJEbuohSlqqQPfD4q+fJT+nArL8D6cgLBoO2mqrqg9Yh2Fk4ZzR5chEq/rg0opuCoHF8eyShhxogF6hNXJADQB1b4pjxRCrP497oq7Dh8oiUdW9eti/CI6FR7k2x3pkdKnYTou0wl35yJvjjUBLZO97KcTz1p2yTJhXGZrYz0YiHRleflPJ/XyNcIzrqCFw3xfdGIkxalehJS/UeC0Q69ypwJ0jQPajdQAJ7eXpf+qaBCDysyrFuPUaa0XE5sGdoQNdfck2Aq9S74k1ZuKd5H42kLzmf6JGNka2kNXFM9B5QZDgQ==,iv:3z+4wVrRpjbPwZTLIz+CfOTUzLl1m3FO2bf9LTCgQOQ=,tag:NJEuVDKbSktsyZ2DAX91nQ==,type:str]
    acl: ENC[AES256_GCM,data:K89ayhVbOCEgJFP6TGMLXtQ3FACkdXctLTJvwV78hQ914aI3DpwNIDWUb4LEEQ3gnzUgDXxCkFySuddSwkmylpdFJpn+bSsIGbRtIgs56MVx/NoccDrxWQKGJok2NZP2+B0=,iv:5SBlJoB94TVr11SDBnD2WedmHwvr86fxiPdvvXlq7Mk=,tag:5L1sFPqxT5N0k8SgDsWafQ==,type:str]
sops:
    age:
        - recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVWtMS24wamZkMVl0ZnlQ
            MnFtOXR4VzFlaUo0MklybjRMTi9iMzdNTjBvCjNlMkNhNkp6dXRuTENOSzdyNlpW
            NGRXL3VBbzFjZzJLd2F0MkFpTDBIbGcKLS0tIHlCM0oyNUdmM2d1MmZNOUh5Umtw
            UmVrR0duZFBpTTJkZk5RQkVPWkxvemsKFqA4dDA+DRnKkxyaQ3gUT9yXGtXxQc9J
            K8osssKHNDfOlZRJVYfUXORg0SRS0WCltgAuK93nL6Lx5Ismdz3Prg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T18:38:06Z"
    mac: ENC[AES256_GCM,data:c9F747PzTFI0H2KjWY4SwuL1SFAFVuTOznbzseNZZ4CGVIGd1ECfEx8NK8izjn4fc+AJEJk2g6kNWIBv7NV4a2GvPJOfPEk7VUowff5jcOfzv7iCxdSpU6Lrea6rrt26nYN4EReH8yiw9Qye2kD3sgp+AtFG6l6/983nzUPlM0g=,iv:v4zGsEJxREsDca3uSl2fBL/XJsx5+58M9V/5/Eb5gqQ=,tag:95xuDVC8RKRm4D4zc3LQzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
