apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-users
  namespace: home
type: Opaque
data:
  passwd: aGFzc2lvOiQ3JDEwMDAkbzZZRlFDK1JSQytzaUF0R3greXVjSnBvREhRZHNVTDBFbzVYMkZmVVBPYUwrb0xsZlBuYXFac1NrZ2lrVHpXNldVN0tBYUhpb0xHMy9OT2lDNkhxOEE9PSRwdndVUzFNcUZ0ZTdyK1FTc2o5MnI2aHdKbWZHL25SdVVialZWYUJtSDRNNWZWTCtWR2VvV3p6Z1NsOTh2bkxPMTZGdm1tTzRJbGNZQnlyd2xBaXNndz09CnoybTokNyQxMDAwJFF2Z3J6OVYzcm9UTmNBZUVoQ25MNUNVdlpzeUZjRlZ5aW9EdU1obVlKMHpGcHhNQnR1UzZ2R1ZlalBHMlg2cjdGd3ZBZFlCVFloL2tVVS9ZcmJ3NVNBPT0kZVVJcmUxMXdWZC93a3llRHBZRldtM0NweUsvdXVyN3JDbFduU1RLZXVkNXVVMFJlRFpZVGtKdE9xUzdRSnR4b2VzSVN1Ty9CMFVDODkreGZ2T0hsZ1E9PQpkZXZpY2U6JDckMTAwMCQ2OFpzRUJNQzlGdFAzTk84Um53aHlJVGV0RFBpOVZwZEVFUktIdndDQ01sN0pKaTlwSVdhaENlejNIaDlEbXNaUWlZdFQ4N0xQUW1GZmdiWThORmEvZz09JGpTblNoNDB3bXJOUUlKa3N0aUVRVFpBVHMxTndwcm00TjV1a1hMS1lqY21YM3JvRkVtWjYrRlFIK09ZY0xOeVlXcytDYVpyTkZmMXJoc2dDdEFiVGJnPT0K
  acl: dXNlciBoYXNzaW8KdG9waWMgcmVhZHdyaXRlICMKCnVzZXIgejJtCnRvcGljIHJlYWR3cml0ZSB6aWdiZWUybXF0dC8jCgp1c2VyIGRldmljZQp0b3BpYyByZWFkIGNvbW1hbmRzL2RldmljZS8jCnRvcGljIHdyaXRlIHNlbnNvcnMvZGV2aWNlLyMK
