apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-users
    namespace: home
type: Opaque
stringData:
    passwd: ENC[AES256_GCM,data:5pWYOcbzS5jV4RB4YhNfBSDyukIIXz7wpfImsYj1ZN3FbI79kwDWBUcxiEgLG6R8dyhwtGb7ENghty8oser+buEb2LvOg5Gea8bw07++6BEMQC3GJqfAjbFv6CGWP0xnX3cKb/dHD/2bZdWmO8XaPfLz/nd5K5a43KcDhcAwpdc/sbx6vu70u4thMWIVPOsGnf7HRDcYr4eRd8MQSJDwE5lk2X4JPA4pinKZ7kcQP/AmBIJWzbihMPFgzNZXq8kFTSCE4tZ2MFajl0OzJjWQ0lWbIP/gFiKydL7992xVdV7/gt8UFIcCw135ZLL9DNk7zW4IL6XrCb27bO2CbtrZOniIpYvu6iJfTfpoKzbdPgG9NUGZK7yydqvXNpZH/ETJDW/CS4HItTZE1yoB3pFMj9okgxqv9oEicQYbj9ZjFMynkPF/8gEIG3sZwIGjbw0wrhSIaolxALpglxdOsM4UNgj0xJkS0GXlc5Ws2aHxVl5o9gSp3wfrmSRJHbiw4+W6EI1M5c9DqTkFur7hXdxCFfO6I6uYamsnMp/fJu2/lUQvbPFqQ5xZtROiYlZN2y9DZ9KLoObuM5ajJPd72wvIqTf3CMFMvlt0APtUhfMdIqRpXWx8/SxOGoSwHOJZUnUBz9wdr5xVTHEjYqpNcyM0yoHc9e1qMzLWpzGxyYoPkgfuLFaELhcKWaY/q1OUFpen1iA9Nt79LRSm+guISwTCv+4iyG8YxH41B0sGUcJxCgJasvsfNYUYE6pCrTymgWcv,iv:idA2w2caDDsLw8yhdePAfmcm33V2JCL3SZIf/I9xZIQ=,tag:9tUtk+nnJivvJFxmDnSigg==,type:str]
    acl: ENC[AES256_GCM,data:j4u0G6KhupPOdwCzOJ6gNaPJSdIhpqVhncmFiqb09OYBpCeDoU6cnf6Z5Rgik0RyVHwQp0qljwlFCdm9O/dJdMXI1uszeakBtekaoLdnk91VhU6eKw704hUR/Z6m7RCcc8Szw6A0h4BuMIiCwOJXon7gZc9FbwcGUX6xX2c7Vw==,iv:DvnevnlAGl/KULu3GLmlpISyC4ehl7BH1hT8iMR1wXQ=,tag:GUFZJ1VNU95/u5+69E+HcA==,type:str]
sops:
    age:
        - recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMG9TazdHNWZidDY3S084
            S2tXNENuY2RpdlJGMUJUczdHMXhDUFVQMGtNCmJVWG1wUEtIa2RobUt5OU5qZUdC
            TlhoQzJFQWhjMHE5YXJTc2lJcHBrTm8KLS0tIFlIOEFPOERmUlVvK3R2ZXBPOVFK
            a1R2eHlaK0hoRmYzLzRTZXhDRHNPL3cKIloSVDXO9K9sm4H8tG/8tg6jsCggFAxk
            2lztJ8DlBtY5yFxkFlAHNmkFVHZZnm1QEqs0ymewcFBZcyuinWxYDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T00:44:01Z"
    mac: ENC[AES256_GCM,data:hRxEJKQ3Fwo/pp5PrY9Wn1iNBVeDBuRcDaLhv6KV3OWIYLz6zgguP7qOl+LPupZhczla9L0Xl1mUewZmQ8dvUl+chp+OjjQcW4eM2Sspg4lvB17AI+AhWotfEbYygeFRc1EGEb1jeM3CJcz/F7KOE37+h54xIa/9SmlLKfA4tJU=,iv:MW8HEKx0pUOM6TUJ6tiynWSmeExxrdfyEdNO7P9MJXQ=,tag:1WmaS/A/8ACvLJdqk3xJJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
