apiVersion: v1
kind: Service
metadata:
  name: valkey
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
spec:
  template:
    spec:
      containers:
        - name: valkey
          resources:
            requests:
              cpu: "1"
              memory: 2Gi
  volumeClaimTemplates:
    - metadata:
        name: valkey-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: lh-fast-block
        resources:
          requests:
            storage: 10Gi
