apiVersion: v1
kind: Secret
metadata:
    name: valkey-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:HTxMZB07yA7BlhrY2dqgld8DfRc6XkJxJ9/MpUi52q8=,iv:EnpBs4iXb+MskmY6qIRLz1cSCJFCUy/nCfE3Lzh0yiY=,tag:F1qI7zmy3HuAFxLyKnKXDA==,type:str]
sops:
    age:
        - recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQ29iM29LRk9FdUVwdzJ1
            SDZqMDdCc1pndjAxQWZYQk9sVmNIOHZudUUwCjVGWEJtVEFhcDErZ0Q0U21hR0VQ
            MVpvdjFKcHRNNVYrSnFpUVlVWVBVMkUKLS0tIEQvdkhKaWRxUGQ3NHlkQ0t3NUZi
            OEJpaC9FUjJhOUp3YS9YY2phRWhiMUEKZ/qUfZ3NInMntnPLeah8pVuJrSaA2w5H
            vuLD6mHXHBKnetZPIpB7GL/D2pCw9RYZHxOFA+mhy3++ZdddWyh9LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:34:24Z"
    mac: ENC[AES256_GCM,data:DGtx7vCgvkZVl78Fjj9JcJEh/842mIFtaEbNmGluGYc911ywAa1QSRS5tw+6VwzoDWi5LpfuzpB+wTF5dVNG/TrDbjeu0XF3Gry8/Cw6mYvepwx2fT8yRgF1PAOy2wkFRuSn1kbIxCRn/tvpQFqPgdyr/N1Gx/widuwbacTQVa8=,iv:CsLqGX0R0PX7Bq10EVsqYDDu2X55mQY7RHlVNGAZiXU=,tag:87T+6DuQ4tX9yIyiFN3IXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
