apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sspti
resources:
  - namespace.yaml
  - ../../../apps/aa-sspti
  - ../../../apps/sspti-skynet
  - secret.yaml
  - configmap.yaml
  - sspti-skynet-secret.yaml
  - sspti-skynet-configmap.yaml
  - aa-sspti-image-automation.yaml
patches:
  - path: pvc-storageclass-patch.yaml
images:
  - name: ghcr.io/vbalexr/aa-sspti
    newTag: 20260529-0325 # {"$imagepolicy":"sspti:aa-sspti:tag"}
  - name: ghcr.io/vbalexr/aa-sspti-nginx
    newTag: 20260529-0326 # {"$imagepolicy":"sspti:aa-sspti-nginx:tag"}
  - name: ghcr.io/mrakaki/sspti-skynet
    newTag: 20260526-2216 # {"$imagepolicy":"sspti:sspti-skynet:tag"}
