apiVersion: v1
kind: Secret
metadata:
    name: aa-sspti-secret
type: Opaque
stringData:
    AA_SECRET_KEY: ENC[AES256_GCM,data:PAABp+UZ7KX3iPcG,iv:DGcp7s9E4xH0lmrHvjzydu+HyoiAFQ0i/U7c8jsD8bo=,tag:ndkEpG4Z0/E6I/14xsVaLQ==,type:str]
    AA_DB_PASSWORD: ENC[AES256_GCM,data:d5/T9c1a2cmqdC39,iv:wI2ETkZwVCNcIhObAvlvN0UIh+CZAADCu6goce3IQZo=,tag:w4fPQZCgiaNWTcKzYXv1Qg==,type:str]
    AA_REDIS_PASSWORD: ENC[AES256_GCM,data:bcdLlKY9EvkP+A8jgjjube6LjC71EwhEUOqaBxp0PAI=,iv:wOscn3gfDx3y66HJBnCoxK5FuKnHnUW7FG2xHbhVwt0=,tag:Kv7H4ue5IFgLtY8RjfFWgw==,type:str]
    ESI_SSO_CLIENT_SECRET: ENC[AES256_GCM,data:8i9Vn/pFfQIsNRPrTVdN+/8IXlTvkg5ZPCSxJR6/+H6XBXGV59KznCDVFBg=,iv:38P2bOQYSTnoZxqUSbj0Ymfu+RyOU3BQGWUVjQmcDkA=,tag:IG9qyLQP0NWQ2Y4jvCZUwg==,type:str]
    DISCORD_APP_SECRET: ENC[AES256_GCM,data:Sq1tG/2r3LjBM2fniVeXoPfHIQp1DRqC+7i1BwdG5aY=,iv:4R8FnRh/Ool3WiEVqGK6afUDWort4NVlVB0kxx1Rw38=,tag:+iFxTe8ilmpa+0lLt1Lybw==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:OWuqVq9B4GC3HBijFHijzEAs6riJD+c+XZPeGBJxD68IODIwdvbYOvdSL2/7sgwuo4PTjOfUKblRnE7yc2gtbyhpiVEfsMIv,iv:Tdj4krUvOPIpmW597d/b3za0WFjRjkTkDnUm73IjbGE=,tag:7hPntvypgXj/6QrKWb2dRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsLzhaN0xjc3RrVUZnSlN1
            ZkVTNzY4V2Uwc2VYcUtobEJsblI3akJvMFdRCmJIeCs5a0xYdjNRMTR6emRsN0p6
            L3BMVTQyeHNnY2dBL1FIYWxpVW02VE0KLS0tIExPUzBLSWx5L29WUGlPMVRMcFpR
            N0lwOHBYNWlxeG4rZXZWc3g4bERZVUUKdcxwssp6Tq9pbG4TuLWHzmJxIHCKETfM
            fVJfPVSyxqIj960LBea2NiGBSZCs8A0Au1OYVy3faijrtYCLV2g7qg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T03:46:19Z"
    mac: ENC[AES256_GCM,data:yZLx3sv9E45RuTG8F4QVyN6AfISmkDg5Fj7bwShp4OGYwixBYdvWKdm4W9+53NwCXcbP/k1c3LrcgqnVoTLzdDO3zdE2feelfU7m/Brz9UODvd8A6Bllp0SOruEWAdKgk1LKh1k7nzfq9DJ7/rGEcvPqCt0mH/hMT1TKTXsWT6w=,iv:pjsGQclT67hEzywmkPkE/sB0y/+gzJQYsjfldGI/83I=,tag:hkbABJB5oZmXWaALyPKImg==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
