apiVersion: v1
kind: Secret
metadata:
    name: aa-sspti-secret
type: Opaque
stringData:
    AA_SECRET_KEY: ENC[AES256_GCM,data:SDOza1gvK2QCduIQ,iv:INOrZjBCxe6tmTvnPkcFBV1o8mvkcDV87oTAVuC6+CM=,tag:3f9rPaiS0IU1I/zr7bmlNg==,type:str]
    AA_DB_PASSWORD: ENC[AES256_GCM,data:lWwqdqnNjZoSciC2,iv:TqCCURKI7C6bzBuBGd4I7bO+0b1BFCYkgHOgStvAH+s=,tag:yPLcYn47fBWD5y1GHQGlEA==,type:str]
    AA_REDIS_PASSWORD: ENC[AES256_GCM,data:KRYgmdF/VshtYReFmbWSJ1aZiekJ47+nwA7U7+sTQmo=,iv:7dzYlYDaU4zFJ1A6NJ0MR9teFyKMSO3k8I7ElLtWCds=,tag:8AkZ9n6MEdyhZoEjgdKXOw==,type:str]
    ESI_SSO_CLIENT_SECRET: ENC[AES256_GCM,data:+FN01XaObYmedSKd/tPD+SMn9rMGeAQxhkibJFuCu69eyaGEGayIlueepT4=,iv:GRU0PWVWu8FCVvacLkUWTelWgqJktrGS1Us20P52MSI=,tag:lZF8WIm5ZNq04pV5PbGfFQ==,type:str]
    DISCORD_APP_SECRET: ENC[AES256_GCM,data:zSmdQh7xQ87nIw93VHanoE8fzOsCeRrFZaOImUseWEU=,iv:BwSeic69kOLnazZUwaJq0P2fJhE7K3D7Dx0acI64qSo=,tag:MZv5PKddZYBA5vi8sAI5fg==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:IXSRuI5tqeq20QjMP80M33LdSaLp1JySDtwT30fyFVWmcVChjFR+j3nG+6JfPcZ4GbDjeKe4cJ+6ysJapE2UiEF08mF6eat7,iv:IUBz8kZOISSfCbK2S7DNC1n8yE/LHpzICtoroEB+N0U=,tag:8otxVnATaozLv8Y0BsJRYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOTBLOXVlUkNzdnFyc2RL
            di9hbWx4UzVHUHlJdzNUaDNtQUNDamF4dURFCjA4ejcrcnpEM3NoaWhvVWdyaFdo
            QWRJSjlKTTdtbHcvaHJMeGxBMGhTV1EKLS0tIG5YTlJ4ZzBxTDVudklzb0paYjh0
            bXpkZHJ4RC9BWmtBVWpaaHIveHlGSXMKARExmByDTcgURwIOLJRxWSmZHhZSimWl
            e7ndWleuWVpYyBn3+HnPDeqFAslAbVJaCDw3nOPaReqDqn7zEBENcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T16:52:00Z"
    mac: ENC[AES256_GCM,data:ANO73lIFE4CD3stFEvPv1nP1VET7es29FhlstfSMyKQ5OSgccoNLgZfy+Kur3WMp9LNS1BfIxZq/wrOM+FsPFG9UJDAneB08peBv8KVlPT3TvjjcsCk95yobSrH/B9k0Ype0/4gOgSCIF4l9SN97K6yOVDQiuk+hiVeqTZesFig=,iv:xP1ger7KeCIjbb2SwUS+HX2Rp2Clju4CDgo0cKxo/6o=,tag:8VGA6ls0Rp8kEy+poBlMXA==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
