apiVersion: v1
kind: Secret
metadata:
    name: sspti-skynet-secret
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:T1P8KtIegSS1wRzYrZ6t3mPu+CeS2DayB2PkIUjUqFBsEvoy3CD13koZEpFC5XgJgLIheLlSyQSMWVoJi+aYnDUlF7XqMBqN,iv:iRCl9zwI93YIszWSKzKIbKAQH7XTDmyUkbJU4vnxDJ0=,tag:jza0IuB0agv6rHtsLBnxpg==,type:str]
    JANICE_API_KEY: ENC[AES256_GCM,data:bYgDM2kolVO8uxjy1R44CxcGH+E4p6KNMy36FBl5FzA=,iv:mqQr8Rs83hmYHI+V+aJipz0F2BrpHNGuTlx512njEeM=,tag:Ot55QNkH+BMG6JSZu/2XAg==,type:str]
    JANICE_BASE_URL: ENC[AES256_GCM,data:XsnxYL7JhPFEUk/A/PElSOs5wrs06nx3si1mLvZggcUZiJsx,iv:pa4uHDTAy3L++Y4LMRzfTxAqxMEMoyiS/PmRc2jQ7yU=,tag:kTAR5bxamdQddEY8pLVOmg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:pjR/8+ep2WTy9awFNjqFU5/ieg9niFt5qyEFkKwPEFTMDmOUIqjB,iv:opXMpKra69Ay0qOdDUwehORsz7NZP7+RgTZx+hoZ9BI=,tag:9aIFdqzaxRP2b0WiZdtQOg==,type:str]
    OPENAI_BASE_URL: ENC[AES256_GCM,data:+adHKs5pg1aX5GNhKowMDLQhdcG81t4t6myJTA5SHjXx2B3FPITx1BNElZqsScN9WluVA+f4dO4=,iv:3Z+bsj3VFdJfZZEyv9PIoJMn9jTs8lCaCmXd/fuBU8E=,tag:1r1vBnjS2I7lBj45PMMz9w==,type:str]
    OPENAI_MODEL: ENC[AES256_GCM,data:NiGe1M4/0jmYa4gw27tYOA==,iv:BjtPfjm8W3rmXIutws6eRVu4IHW+mUEueVY0m0xK3vo=,tag:QFMHxvvDFVoqTPSztF9Vjg==,type:str]
    OPENAI_MAX_TOOL_HOPS: ENC[AES256_GCM,data:pg==,iv:Cko7G0h8y6zgax249IYoh3OPX2If9d0TWorHzni/U2g=,tag:1gKkjusXbUp8Z6+pTjKN1A==,type:str]
    OPENAI_MAX_REFINEMENT_HOPS: ENC[AES256_GCM,data:LA==,iv:mvLJsG34XsFsf87p4J1zfsJo/hgbm/mko0i20DqPtRY=,tag:efB2xBWd545fOc2pLSPK7g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:cRPdA3/raINET1K8ggbtAzPbfrkj9IDvU9ymp/tN9DqOK6O0ZCSw8gZQNdxMNML0pYfYbING5eIN9SvqRyRxGvKL/6QU8VguhkpZGcQOPdTUbB3LntHWQtQLE8/4m20=,iv:oHaAhlq6t/3vto2RCdLZu29TsnliKDSLYkWHHUfXDwk=,tag:9uMdpbCLtXr27mtPy0U9JA==,type:str]
    ESI_USER_AGENT: ENC[AES256_GCM,data:KDZXhMLe29u6mPw1Oa5THD3zIqh/l8UvBTZ7uJjw583DTNGCm2pK4g==,iv:4vep7QTROpMbCZvb3C1ANMT0c3jH7ADUp1gbMwvoMF8=,tag:A8CaUlICRyOCUERaET/6rg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dE1qVmhTUytsTUZFenZG
            QW01UzFPM3pKbmc1OHRRNmo5blV4TlB0SFcwCk1FOTdvbDViNEpyanhOc25TdzdO
            U1FsOW9GQW80aWxHbnBIY2lOcFBjazQKLS0tIFFPM0ZQUVZDR3ZpZzNERmpSUFNo
            VFpkSGVmS1NaT2R0Nk8vYkZwcisyVEEKHU0MWxR+tYYIMLqeKM5XOeVyA6xxHH6E
            hmfP8/DcS+/d8sqLeu1xiTw7YvTdnYQLJC1HDzKIlXJdNS+e8+XoCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T23:03:41Z"
    mac: ENC[AES256_GCM,data:RedRQvYKMglj0VKjbm1hDGDV2UBSBXm1CFITVkW0mJpLTYXq1w4tfNGnOeMCQWxS95s2ENX+J1qY2hvry9aTy4obJPHj0feaJjUvoJRg9t0Eoyia1n+rMltzB4d06FJAS1nOJtaSBGTfK8wfP8AiPHdATx2AEDdQ/uB13bn7G9M=,iv:C87HOE/lDqVkm+QOhpxdR/x1vo36n9n4CmaM6MGb4d0=,tag:z/FgXyjaF8AvzCgOwmJFVQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
