apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ../../../../apps/mariadb
  - secret.yaml
  - service-lb.yaml
  - configmap.yaml
patches:
  - path: patches.yaml
