apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-headless
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  template:
    spec:
      containers:
        - name: mariadb
          resources:
            requests:
              cpu: "2"
              memory: 8Gi
          volumeMounts:
            - name: mariadb-config
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: mariadb-config
          configMap:
            name: mariadb-config
  volumeClaimTemplates:
    - metadata:
        name: mariadb-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: lh-fast-block
        resources:
          requests:
            storage: 128Gi
