apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secret
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:kP9tN7jBNcvwM2jJS38UkuP47O87A9SA7S+gQajbseg=,iv:W76PGHlUchAe968iJ7zFBy9r7sYaDo+oNmyNdiHBjmU=,tag:g6pm/Ozs3QAFVOnuIUYh7g==,type:str]
sops:
    age:
        - recipient: age1meluhn5ap2s46h7668rmumz30020shyh7h9jtz6ae0428kxhyagqfpzla0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHM1c4TlVjRFo5UG16OEh6
            Vy8xOHhveXJRaGdaTWZpazVyS1lFZUYwbEUwClZscy9neXdsQXV2T053RU1aTFU2
            c3huUmFsZEFxcmZoanUvT2NINEIzdGMKLS0tIE0xS3JGTHJpekRyZFNDKzdGdXI2
            OUNwSGFtUnZ2bEVXaUg1c0JTak9FSncKE/hVslZTiUulk1jT+uL4t+ZXiYeEjDIX
            Ha6ZZt040gPfmwVpswsuAr9qdW3cFSO9mZWhXg8HV9Ml14OqKAErhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:34:18Z"
    mac: ENC[AES256_GCM,data:oOVjQVpULWcrc4JNN3oAvB6xhPa+8JgvJBk0VDs3KnWkG0OsBYWuw+IxNHZAEgHIgHIfeiLMX21OL76/jVotvgtHC3DAMWB67u2JAT2ajhXQaKoXTPyyWyQQz7k18afvzZ0stumVVuEU20V86Mv6xrbb5jSmJNlO1jr3bZB14SY=,iv:+/iBl02O/CyMKqbbquVdTxZztURtc0RpkwveqqPjkeI=,tag:b9KsL0PTJIawmDoRwbv8tw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
