apiVersion: v1
kind: Service
metadata:
  name: mariadb-lb
  labels:
    app: mariadb
    pool: private
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
